---
categories:
- JavaScript
date: '2023-07-23'
title: '[JavaScript] 15. Exception'
---

{% raw %}
### 예외 처리 (Exception Handling)
- 자바스크립트에선 예외 처리를 담당하는 `try / catch / finally`문을 제공합니다.
- `try`: 처음으로 실행되는 영역입니다. 이 구간에서 예외가 발생하면 즉시 catch로 이동합니다.
- `catch`: 예외 발생시 실행되는 영역입니다. 인자로 throw가 던져준 값을 갖습니다.
	- catch의 인자는 생략할 수 있습니다.
- `finally`: 예외 상관없이 항상 마지막에 실행되는 영역입니다.
- catch, finally는 반드시 사용하지 않아도 되는 선택적인 옵션입니다.
- `throw`: 예외를 발생시키는 키워드
	- number, Error 객체 등 대부분 타입이 올 수 있으며, 이 값은 catch의 인자로 전달됩니다.
- `Error`: 에러 정보를 저장하는 표준 객체
- 자바스크립트에서 런타임 오류가 발생하면, 해당 오류 정보를 저장하는 Error 객체의 인스턴스가 생성됩니다.

```
try {
	// 예외가 발생할 수 있는 작업 영역
}
catch (`error`) {
	// 예외 발생시 실행되는 영역
}
finally {
	// try나 catch 구간이 끝나고 실행되는 영역
}
```

```
var loop = true;
while(loop) {
	try {
		var word = prompt("길이가 2-3인 단어를 입력하세요.", "");
		if(word.length <= 3) {
			if(word.length >= 2)
				alert("입력된 단어는 " + word + "입니다.");
			else
				throw 0;
		}
		else
			throw 1;
	}
	catch(e) {
		if(e == 0)
			alert("단어 길이가 2보다 작습니다.");
		else
			alert("단어 길이가 3보다 큽니다.");
	}
	finally {
		loop = confirm("계속 진행할까요?");
	}
}
```

### 비동기 (Asyncronous)
- 자바스크립트는 오류가 발생하면 호출 스택을 되감는 과정을 거칩니다. 이 과정 중에 try 블록을 만나야 예외 처리를 할 수 있습니다.
- 그렇기에 비동기의 예외 처리는 동기와는 다른 점이 있습니다.

#### 콜백 (Callback)
- 비동기 콜백 내부에서 발생한 오류는 콜백 내부의 try 블록으로 잡아야 합니다. (비동기 콜백의 실행 과정 특성상, 콜백 외부의 try 블록으로는 콜백 내부의 오류를 잡을 수 없습니다.)

```
setTimeout(() => {<br>
	try {
		throw new Error('Error!');
	} catch (e) {
		console.error(e);
	}
}, 0);
```

#### Promise
- Promise.prototype의 `then` 메소드는 2개의 콜백 인자를 가질 수 있습니다. 이중 2번째 콜백은 현재 Promise가 `rejected` 상태일 때 호출됩니다.
- 2번째 콜백의 인자는 Error 객체입니다.

```
const p = new Promise((resolve, reject) => {<br>
	setTimeout(() => { throw new Error('Error!'); }, 0);<br>
});

p.then(res => console.log('여기는 실행되지 않습니다.'), <br>
	err => console.log(err)); // 이 콜백이 실행됩니다.<br>
```

- Promise.prototype의 `catch` 메소드를 사용할 수도 있습니다. `catch` 메소드는 1개의 콜백을 인자로 하며, 이 콜백은 현재 Promise가 `rejected` 상태일 때 호출됩니다.
- 이 콜백의 인자도 Error 객체입니다.

```
Promise.resolve()
	.then(res => { throw new Error('Error!'); })<br>
	.then(res => console.log('여기는 실행되지 않습니다.'))<br>
	.catch(err => console.log(err))<br>
	.then(res => console.log('여기는 실행됩니다.'));<br>
```

#### 비동기 함수 (Async Function)
- `비동기 함수`의 예외 처리는 동기식 예외 처리처럼 작성할 수 있습니다.
- `await`에 걸린 Promise 객체의 오류는 비동기 함수 내부의 try 블록으로 잡을 수 있습니다. 이때 catch의 1번째 인자는 해당 Promise의 오류 정보를 저장합니다.
	- await를 사용하지 않았다면 try 블록으로 잡히지 않습니다.

```
async function timer(s) {
	return new Promise(resolve => { throw new Error('Error!'); }, s);<br>
}
async function main() {
	try {
		await timer(1000);
	} catch(e) {
		console.log(e);
	}
}
main();
```

### strict 모드
- `strict 모드`는 자바스크립트 코드에 보다 엄격한 오류 검사와 향상된 보안 기능을 제공합니다.
- 스크립트나 함수의 맨 처음에 다음 지시어를 추가하면, 해당 블록에 strict 모드가 적용됩니다.
	- ES2015 모듈로 작성된 코드는 항상 strict 모드로 동작합니다.

> "use strict"<br>

strict 모드에서 대표적인 변경사항은 다음과 같습니다.
- 선언되지 않은 변수는 사용 불가
- eval() 함수 내에서 선언된 변수는 외부에서 사용 불가
- 읽기 전용 프로퍼티에 대입 불가
- 한 프로퍼티를 여러 번 정의 불가
- 함수를 구문이나 블록 내에서 선언 불가
- 중복된 매개변수 불가
- arguments 객체의 요소 값 변경 불가
- 전역에서 함수 호출시, this가 undefined 반환
- 문자열 "eval", "arguments" 사용 불가
- delete 키워드 사용 불가
- with 문 사용 불가
- 일부 예약어 사용 불가
{% endraw %}